# Dependencies

In [1]:
import pandas as pd

# Targets:

1. Fix data types of the dataset [dtypes]
2. Fix column names to not have spaces and have short names.
    2.1 Also, prepare data dictionary for new column names.
3. Create better features [by combining some columns]
4. Check co-relation and highlight highly correlated variables
5. Remove correlated variables
6. Get Count, Average, min and max for each month by each year of all numerical fields.
7. ***[Advanced step]*** Based on all above steps compute relative change:
    7.1 Monthly
    7.2 Yearly
    
*** Also, implement everything else that you find important for this analysis***

# Resources

This is a good introductory python repository for Exploratory Data Analysis.

<a href="https://github.com/cmawer/pycon-2017-eda-tutorial/tree/master/notebooks"> EDA Tutorial</a>

# Reading Data

In [2]:
df = pd.read_csv('data.csv')
ncol = df.shape[1]
# changed the option of head to display all columns
pd.set_option('display.max_columns', ncol)

# if dataset is not very large then head else
df.head()

# df.sample(5)

,Unnamed: 0,Year,Month,Net generation other renewables (total) (thousand megawatthours),Average retail price of electricity (cents per KWH),Retail sales of electricity (million kilowatthours),Revenue from retail sales of electricity total(million dollars),Revenue from retail sales of electricity residential (million dollars),Total consumption coal (thousand tons),Total consumption petroleum liquid (thousand barrels),Total consumption natural gas (thousand Mcf),unqid,kt_avg,T2M_avg,WS10M_avg,State,kt_max,T2M_max,WS10M_max,kt_min,T2M_min,WS10M_min,"for wind , Power = 1.93 * V^3 * R^2 * Cp , in watts","for solar , 1367 * kt * r ^ 2 * efficiency",total_renewable_policy_count,Wind_policy_count,Solar_photovoltaic_policy_count
0,0,2017,7,303.5966,12.53,3429.51828,878.76993,429.58206,1858.693,3.938,42893.952,2017_7_Alabama,0.558278,27.427392,1.380161,Alabama,0.71,30.42,3.20,0.08,24.62,0.43,"Cp is max power coefficient , varies from 0.25...",r is length of solar array,37,5,7
1,1,2017,6,279.92249,12.79,2727.88024,766.67053,348.87341,1489.063,2.741,33357.656,2017_6_Alabama,0.470984,24.293833,1.712028,Alabama,0.71,27.62,4.20,0.06,19.44,0.79,r is radius of swept area in meters,"efficiency , varies from 14 to 24 % , max of ...",37,5,7
2,2,2017,5,274.68961,12.73,2262.40423,681.01506,287.89061,1310.503,4.459,30762.064,2017_5_Alabama,0.536478,21.701156,2.037876,Alabama,0.75,27.64,4.59,0.10,9.62,0.85,V is wind speed in m/s,kt we have,37,5,7
3,3,2017,4,268.04368,12.71,2044.88955,623.23465,259.84629,1130.11,3.524,29599.447,2017_4_Alabama,0.585944,19.618250,2.277944,Alabama,0.77,26.37,5.69,0.04,9.62,0.91,NaN,NaN,37,5,7
4,4,2017,3,272.50137,12.82,2127.99069,643.88836,272.88091,1271.181,5.062,30229.111,2017_3_Alabama,0.530641,13.752742,2.474113,Alabama,0.76,22.85,4.59,0.04,0.22,1.11,Note : for other columns,NaN,37,5,7

In [3]:
# Getting index for the columns in dataframe

columnnames = df.columns
for i in range(len(columnnames)):
    print('index: {} \tcolumn name:  {}'.format(i, columnnames[i]))

index: 0 	column name:  Unnamed: 0
index: 1 	column name:  Year
index: 2 	column name:  Month
index: 3 	column name:  Net generation other renewables (total)  (thousand megawatthours)
index: 4 	column name:  Average retail price of electricity (cents per KWH)
index: 5 	column name:  Retail sales of electricity (million kilowatthours)
index: 6 	column name:  Revenue from retail sales of electricity total(million dollars)
index: 7 	column name:  Revenue from retail sales of electricity residential (million dollars)
index: 8 	column name:  Total consumption coal (thousand tons)
index: 9 	column name:  Total consumption petroleum liquid (thousand barrels)
index: 10 	column name:  Total consumption  natural gas (thousand Mcf)
index: 11 	column name:  unqid
index: 12 	column name:  kt_avg
index: 13 	column name:  T2M_avg
index: 14 	column name:  WS10M_avg
index: 15 	column name:  State
index: 16 	column name:  kt_max
index: 17 	column name:  T2M_max
index: 18 	column name:  WS10M_max
index: 19 	column name:  kt_min
index: 20 	column name:  T2M_min
index: 21 	column name:  WS10M_min
index: 22 	column name:  for wind , Power = 1.93 * V^3 * R^2 * Cp , in watts
index: 23 	column name:  for solar , 1367 * kt * r ^ 2 * efficiency
index: 24 	column name:  total_renewable_policy_count
index: 25 	column name:  Wind_policy_count
index: 26 	column name:  Solar_photovoltaic_policy_count